#pragma once
#ifndef ENUMS_H
#define ENUMS_H

// 元素类型枚举
enum ElementType {
    TYPE_INPUT, TYPE_OUTPUT, TYPE_AND, TYPE_OR, TYPE_NOT, TYPE_XOR,
    TYPE_NAND, TYPE_NOR, TYPE_WIRE, TYPE_SELECT, TYPE_TOGGLE_VALUE,
    TYPE_CLOCK, TYPE_RS_FLIPFLOP, TYPE_D_FLIPFLOP, TYPE_JK_FLIPFLOP,
    TYPE_T_FLIPFLOP, TYPE_REGISTER, ID_TOGGLE_TREE
};

#endif
